### ISSUE TITLE
bug: Not using multiple GPUs

### ISSUE THREAD

**Issue by lazorfuzz** [bentoml/OpenLLM#1168]
### Describe the bug

Trying to run llama 90b vision on a VM with 4 A-100s.

Logs indicate `tensor_parallel_size=1`. But it should be 4 right?

```
nvidia-smi
Sat Apr  5 00:47:34 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.127.05             Driver Version: 550.127.05     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100 80GB PCIe          On  |   00000001:00:00.0 Off |                    0 |
| N/A   37C    P0             55W /  300W |       1MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA A100 80GB PCIe          On  |   00000002:00:00.0 Off |                    0 |
| N/A   38C    P0             57W /  300W |       1MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA A100 80GB PCIe          On  |   00000003:00:00.0 Off |                    0 |
| N/A   39C    P0             57W /  300W |       1MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA A100 80GB PCIe          On  |   00000004:00:00.0 Off |                    0 |
| N/A   37C    P0             56W /  300W |       1MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
```

### Logs

```shell
2025-04-05T00:44:39+0000 [INFO] [entry_service:llama3.2:1] Service llama3.2 initialized
2025-04-05T00:44:39+0000 [INFO] [entry_service:llama3.2:1] Running startup hook: init_engine
2025-04-05T00:44:42+0000 [INFO] [entry_service:llama3.2:1] Automatically detected platform cuda.
2025-04-05T00:44:49+0000 [WARNING] [entry_service:llama3.2:1] To see benefits of async output processing, enable CUDA graph. Since, enforce-eager is enabled, async output processor cannot be used
2025-04-05T00:44:49+0000 [WARNING] [entry_service:llama3.2:1] Found PROMETHEUS_MULTIPROC_DIR was set by user. This directory must be wiped between vLLM runs or you will find inaccurate metrics. Unset the variable and vLLM will properly handle cleanup.
2025-04-05T00:44:49+0000 [INFO] [entry_service:llama3.2:1] Started engine process with PID 36653
2025-04-05T00:44:52+0000 [INFO] [] Automatically detected platform cuda.
2025-04-05T00:44:53+0000 [INFO] [] Initializing a V0 LLM engine (v0.8.2) with config: model='/home/leonli/.cache/huggingface/hub/models--meta-llama--llama-3.2-90b-vision-instruct/snapshots/e305d2a43a4adc6987308fe7d896fb8ec5f1a5d8', speculative_config=None, tokenizer='/home/leonli/.cache/huggingface/hub/models--meta-llama--llama-3.2-90b-vision-instruct/snapshots/e305d2a43a4adc6987308fe7d896fb8ec5f1a5d8', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=16384, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar', reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=None, served_model_name=meta-llama/Llama-3.2-90B-Vision-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=None, chunked_prefill_enabled=False, use_async_output_proc=False, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[],"max_capture_size":0}, use_cached_outputs=True, 
2025-04-05T00:44:54+0000 [INFO] [] Using Flash Attention backend.
^C2025-04-05T00:44:55+0000 [INFO] [] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0
2025-04-05T00:44:55+0000 [INFO] [] Starting to load model /home/leonli/.cache/huggingface/hub/models--meta-llama--llama-3.2-90b-vision-instruct/snapshots/e305d2a43a4adc6987308fe7d896fb8ec5f1a5d8...
2025-04-05T00:44:55+0000 [ERROR] [] CUDA out of memory. Tried to allocate 448.00 MiB. GPU 0 has a total capacity of 79.14 GiB of which 438.75 MiB is free. Including non-PyTorch memory, this process has 78.70 GiB memory in use. Of the allocated memory 78.07 GiB is allocated by PyTorch, and 156.49 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/home/leonli/.openllm/venv/1478283038058225095/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 436, in run_mp_engine
    engine = MQLLMEngine.from_vllm_config(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leonli/.openllm/venv/1478283038058225095/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 128, in from_vllm_config
    return cls(
           ^^^^
  File "/home/leonli/.openllm/venv/1478283038058225095/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 82, in __init__
    self.engine = LLMEngine(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leonli/.openllm/venv/1478283038058225095/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 280, in __init__
    self.model_executor = executor_class(vllm_config=vllm_config, )
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leonli/.openllm/venv/1478283038058225095/lib/python3.11/site-packages/vllm/executor/executor_base.py", line 52, in __init__
    self._init_executor()
  File "/home/leonli/.openllm/venv/1478283038058225095/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 47, in _init_executor
    self.collective_rpc("load_model")
  File "/home/leonli/.openllm/venv/1478283038058225095/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 56, in collective_rpc
    answer = run_method(self.driver_worker, method, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leonli/.openllm/venv/1478283038058225095/lib/python3.11/site-packages/vllm/utils.py", line 2255, in run_method
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/leonli/.openllm/venv/1478283038058225095/lib/python3.11/site-packages/vllm/worker/worker.py", line 183, in load_model
    self.model_runner.load_model()
  File "/home/leonli/.openllm/venv/1478283038058225095/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 1113, in load_model
    self.model = get_model(vllm_config=self.vllm_config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leonli/.openllm/venv/1478283038058225095/lib/python3.11/site-packages/vllm/model_executor/model_loader/__init__.py", line 14, in get_model
    return loader.load_model(vllm_config=vllm_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leonli/.openllm/venv/1478283038058225095/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py", line 441, in load_model
    model = _initialize_model(vllm_config=vllm_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leonli/.openllm/venv/1478283038058225095/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py", line 127, in _initialize_model
    return model_class(vllm_config=vllm_config, prefix=prefix)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leonli/.openllm/venv/1478283038058225095/lib/python3.11/site-packages/vllm/model_executor/models/mllama.py", line 1171, in __init__
    self.language_model = MllamaForCausalLM(
                          ^^^^^^^^^^^^^^^^^^
  File "/home/leonli/.openllm/venv/1478283038058225095/lib/python3.11/site-packages/vllm/model_executor/models/mllama.py", line 1109, in __init__
    self.model = MllamaTextModel(vllm_config=vllm_config,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leonli/.openllm/venv/1478283038058225095/lib/python3.11/site-packages/vllm/model_executor/models/mllama.py", line 1049, in __init__
    LlamaDecoderLayer(
  File "/home/leonli/.openllm/venv/1478283038058225095/lib/python3.11/site-packages/vllm/model_executor/models/llama.py", line 252, in __init__
    self.mlp = LlamaMLP(
               ^^^^^^^^^
  File "/home/leonli/.openllm/venv/1478283038058225095/lib/python3.11/site-packages/vllm/model_executor/models/llama.py", line 77, in __init__
    self.down_proj = RowParallelLinear(
                     ^^^^^^^^^^^^^^^^^^
  File "/home/leonli/.openllm/venv/1478283038058225095/lib/python3.11/site-packages/vllm/model_executor/layers/linear.py", line 1169, in __init__
    self.quant_method.create_weights(
  File "/home/leonli/.openllm/venv/1478283038058225095/lib/python3.11/site-packages/vllm/model_executor/layers/linear.py", line 178, in create_weights
    weight = Parameter(torch.empty(sum(output_partition_sizes),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leonli/.openllm/venv/1478283038058225095/lib/python3.11/site-packages/torch/utils/_device.py", line 104, in __torch_function__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 448.00 MiB. GPU 0 has a total capacity of 79.14 GiB of which 438.75 MiB is free. Including non-PyTorch memory, this process has 78.70 GiB memory in use. Of the allocated memory 78.07 GiB is allocated by PyTorch, and 156.49 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

### Environment

`bentoml`: 1.4.7
`python`: 3.13.2
`platform`: Linux-6.8.0-1017-azure-x86_64-with-glibc2.35
`uid_gid`: 1000:100

**Comment by aarnphm** [comment]
Can you try to use the nightly repo?

```bash
openllm repo add nightly https://github.com/bentoml/openllm-models@nightly
```

Then do `openllm serve --repo nightly`

**Comment by aarnphm** [comment]
This is now fixed on the latest openllm models repo main
